-- Demo table used by HomePage to verify the Supabase wiring works.
-- Apply with: npx supabase db push

create table if not exists public.test (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text
);

alter table public.test enable row level security;

-- Without a SELECT policy, RLS silently returns zero rows (no error)
create policy "Authenticated users can read test items"
on public.test for select
to authenticated
using (true);

insert into public.test (name)
values ('First test item'), ('Second test item');
